### ISSUE TITLE
Can't seem to get past google login, just see a spinning wait post google auth screens?

### ISSUE THREAD

**Issue by mistyn8** [googlecodelabs/photos-sharing#16] opened 2020-01-21 14:07 UTC
So followed up to step 4.
I don't get any errors and see the usual google signin and allow perms on the app authentication screens so that seems ok?
I just sit at a rotating green icon.... never getting to the Create/join trip album screen...

I did see that adding the scopes gives a  " Needs verification
Because you're using one or more sensitive scopes, your app registration requires verification by Google.Please edit your app to submit for verification" would this cause the never really completes the signin?

cheers

**Comment by ciprianprohozescu** [comment] 2020-02-01 12:59
I have the same issue.

**Comment by mohammad19-meet** [comment] 2020-03-08 13:11
It has been almost 10 months and the same error is still present. The rotating progress bar keeps on spinning with no errors in sight. It is clearly not a problem in the code so what can it be cause by ? 

It would be very helpful if someone who might have encountered the same issue and resolved it to share how he fixed it.

Thank you

**Comment by jfschmakeit** [comment] 2020-03-09 06:05
Did you follow the steps in step 4 in the codelab "Enable the Google Photos Library API", in particular your Google developers project needs to have a "support email address" configured. You don't need to submit it for verification, but this page needs to include your OAuth scopes and email address. See also issue  #7 

Having said that, I'll try to reproduce this issue to see if there's an issue with the codelab itself.

**Comment by pixnbit** [comment] 2020-03-15 21:20
I did some debugging. The reason is that the onCurrentUserChanged callback to update `_currentUser` is after the `signIn` or `signInSilently` async calls. (Not sure it's a bug or the google_sign_in behavior changed). Here is my fix:

(Update all your libraries to latest in the pubspec.yaml) In PhotosLibraryApiModel:

```
class PhotosLibraryApiModel extends Model {
  PhotosLibraryApiModel() {
    _googleSignIn.onCurrentUserChanged.listen((GoogleSignInAccount account) {
      _currentUser = account;
      if (client == null) {
        client = PhotosLibraryApiClient(_currentUser.authHeaders);
        updateAlbums();
      } else {
        notifyListeners();
      }
    });
  }
```

**Comment by SusannaJung** [comment] 2020-03-16 02:15
@pixnbit  Thank you! It worked for me

**Comment by jfschmakeit** [comment] 2020-04-24 05:42
We have a fix for this ready and should be pushing out an update to the codelab next week. Please stay tuned!

The workaround mentioned above should work in the meantime.

**Closed as completed** 2020-04-28 06:05 UTC
